### ISSUE TITLE
@import within @if

### ISSUE THREAD

**Issue by x35a** [felics/dry-animate#1] opened 2015-05-11 21:09 UTC
hi, in _scaffold.scss you use @import inside @if directive. I'm getting compile error (ruby Sass 3.4.9)

```
Error: Import directives may not be used within control directives or mixins.
```

How do u handle it?

**Comment by fspoettel** [comment] 2015-05-20 11:10
@rosivanov you are right here, libsass allows this but really shouldn't according to spec. I'll move the conditional to the files itself and update the package with a new semver (`0.3.0`). asap

**Comment by fspoettel** [comment] 2015-05-20 12:33
@rosivanov fixed on master & bower release as of `0.3.0`

**Comment by x35a** [comment] 2015-05-20 17:34
@felics hi, i moved to libsass but faced another problem. seems like my libsass doesnt handle @at-root properly.
import and invoke mixin

```
@import 'bower_components/dry-animate/scss/dry-animate';

.sample {
    @include animate(fadeIn);
}
```

and this is output css

```
.sample {
  @at-root {
    @keyframes fadeIn {
      0% {
        opacity: 0; }
      100% {
        opacity: 1; } }
 }
 }
```

i'm trying to figure out is this only my libsass fail ?

**Comment by fspoettel** [comment] 2015-05-20 17:36
Are you on the latest libsass?

**Comment by x35a** [comment] 2015-05-20 17:53
Not sure. I use prepros for compiling and there no word about libsass ver.

**Comment by fspoettel** [comment] 2015-05-20 18:07
@rosivanov I cannot replicate the issue. @at-root was added to lib-sass recently (in 3.2 about 2 weeks ago) so the problem is most likely on prepros site.

**Comment by x35a** [comment] 2015-05-20 18:12
@felics yep, i think so too. thanks for feedback.

**Comment by fspoettel** [comment] 2015-05-20 20:57
@rosivanov @at-root is used a synthactical sugar to modularize the keyframes-declaration in the placeholder-selector. You could absolutely move it out of the declaration to get rid of it if you really need to.

**Comment by x35a** [comment] 2015-05-20 21:22
@felics  i've been trying but if i move out @at-root, i receive this output in css

```
.sample {
  animation: bounce 1s 0s 1;
  animation-fill-mode: both; 
}
.sample {
  transform-origin: center bottom;
  @keyframes bounce {
  ......
  }
}
```

**Comment by fspoettel** [comment] 2015-05-20 22:02
Do you have npm installed on your machine? if so, can you open a terminal in the dry-animate directory and run `npm install` and then `gulp test` in the dir and post the content of `./_test/build/all.css`?

**Comment by fspoettel** [comment] 2015-05-20 22:03
@rosivanov in any case, it should work with ruby-sass now. I can built the tests with the latest versions of ruby-sass and lib-sass packaged in gulp-sass and gulp-ruby-sass just fine

**Comment by x35a** [comment] 2015-05-20 23:01
@felics it works fine with ruby-sass, dont worry) 
Obviously my prepros works with out of date libsass version and therefore it cant handle code proper. And eventually i have to jump off from prepros to libsass+grunt or gulp.
Like a temporary solution i forked ur repo and made some changes in order to force my libsass to produce correct output.

**Comment by fspoettel** [comment] 2015-05-20 23:04
alright, closing this down for now!

**Closed as completed by fspoettel** 2015-05-20 23:04 UTC
Labels: bug

**Comment by fspoettel** [comment] 2015-05-21 00:42
@rosivanov I removed at-root from the repo as it is not really needed, so prepros should now work for you!

**Comment by x35a** [comment] 2015-05-21 12:02
@felics it works, thank you, appreciate it !
the one thing i noted is that i get full list of @keyframes in css file even if $da-animations is not 'all'. Looks like da-import() returns 'true' whatever $da-animations is, even if $da-animations: (123). But never mind, i realize this is my prepros fault.
